services:
  - type: web
    name: site-cronicas-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /health
    envVars:
      - key: ALLOWED_VOTE_IPS
        sync: false
